export default [
	{
		name: "Heliodex",
		username: "heliodex",
		skills: ["Node.JS", "Svelte & SvelteKit", "HTMX & Go", "Wix"],
		skillNames: ["Svelte", "SvelteKit", "Node.JS", "Wix", "Go"],
	},
	{
		name: "Taskmanager",
		username: "task.mgr",
		skills: ["PHP", "Node.JS", "C# & ASP.NET", "Svelte & SvelteKit"],
		skillNames: ["PHP", "Node.JS", "C#", "ASP.NET", "Svelte", "SvelteKit"],
	},
	{
		name: "sushi",
		username: "SushiDesigner",
		skills: ["Svelte & SvelteKit", "Node.JS", "Rust"],
		skillNames: ["Node.JS", "Svelte", "SvelteKit", "Rust"],
	},
	{
		name: "Pizzaboxer",
		username: "boxerpizza",
		skills: ["PHP", "Node.JS", "C# & ASP.NET"],
		skillNames: ["PHP", "Node.JS", "C#", "ASP.NET"],
	},
	{
		name: "KJF",
		username: "kjf_cs",
		skills: ["PHP", "C# & ASP.NET"],
		skillNames: ["PHP", "C#", "ASP.NET"],
	},
	{
		name: "Kyle Wagness",
		username: "RbxXlXi",
		skills: ["PHP", "Node.JS", "React & Next"],
		skillNames: ["PHP", "Node.JS", "React", "Next"],
	},
	{
		name: "EnergyCell",
		username: "Icseon",
		skills: ["PHP", "Node.JS", "Vue & Nuxt"],
		skillNames: ["PHP", "Node.JS", "Vue", "Nuxt"],
	},
	{
		name: "Raymonf",
		username: "r4ymonf",
		skills: ["PHP", "Node.JS", "React & Next"],
		skillNames: ["PHP", "Node.JS", "React", "Next"],
	},
	{
		name: "Kinery",
		username: "kineryy",
		skills: ["PHP", "PHP & Laravel", "Node.JS"],
		skillNames: ["PHP", "Laravel", "Node.JS"],
	},
	{
		name: "Stan",
		username: "stanc",
		skills: ["PHP", "PHP & Laravel"],
		skillNames: ["PHP", "Laravel"],
	},
	{
		name: "Casenn",
		username: "casennx",
		skills: ["PHP", "PHP & Laravel"],
		skillNames: ["PHP", "Laravel"],
	},
	{
		name: "Carrot",
		username: "rjindael",
		skills: ["PHP", "PHP & Laravel", "Rust"],
		skillNames: ["PHP", "Laravel", "Rust"],
	},
	{
		name: "qzip",
		username: "ui0ppk",
		skills: ["PHP", "Node.JS"],
		skillNames: ["PHP", "Node.JS"],
	},
	{
		name: "Multako",
		username: "skulyire",
		skills: ["PHP", "Node.JS"],
		skillNames: ["PHP", "Node.JS"],
	},
	{
		name: "debian",
		username: "kickturn",
		skills: ["PHP", "Node.JS"],
		skillNames: ["PHP", "Node.JS"],
	},
	{
		name: "unexp",
		username: "unexp",
		skills: ["Node.JS"],
		skillNames: ["Node.JS"],
	},
	{
		name: "alonso",
		username: "SimplyAlonso",
		skills: ["PHP"],
		skillNames: ["PHP"],
	},
	{
		name: "BrentDaMage",
		username: "System_Address",
		skills: ["PHP", "C# & ASP.NET"],
		skillNames: ["PHP", "C#", "ASP.NET"],
	},
	{
		name: "XyDark",
		username: "ZYBrights",
		skills: ["C# & ASP.NET"],
		skillNames: ["ASP.NET"],
	},
	{
		name: "Carly",
		username: "theofficial608",
		skills: ["PHP"],
		skillNames: ["PHP"],
	},
	{
		name: "Ahead",
		username: "ahe4d",
		skills: ["PHP", "PHP & Laravel", "Node.JS"],
		skillNames: ["PHP", "Laravel", "Node.JS"],
	},
	{
		name: "Aep",
		username: "6aep",
		skills: ["C# & ASP.NET"],
		skillNames: ["ASP.NET"],
	},
]
